# For help please either refer to the
# the bukkit dev page: http://dev.bukkit.org/bukkit-plugins/superwheat/
message: '&6[SuperWheat] That plant is not fully grown yet!'
message-enabled: true
creative:
  dropsCreative: false
  blockCreativeDestroying: false
wheat:
  enabled: true
  trampling: true
  delayHit: 3
  water:
    delay: 5
    drops:
      wheat: true
      seed: false
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      wheat: true
      seed: false
    prevent:
      premature: true
      mature: false
netherWart:
  enabled: true
  delayHit: 3
  water:
    delay: 5
    drops:
      netherWart: true
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      netherWart: true
    prevent:
      premature: true
      mature: false
cocoaPlant:
  enabled: true
  delayHit: 3
  water:
    delay: 5
    drops:
      cocoaPlant: true
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      cocoaPlant: true
    prevent:
      premature: true
      mature: false
carrot:
  enabled: true
  trampling: true
  delayHit: 3
  water:
    delay: 5
    drops:
      carrot: true
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      carrot: true
    prevent:
      premature: true
      mature: false
potato:
  enabled: true
  trampling: true
  delayHit: 3
  water:
    delay: 5
    drops:
      potato: true
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      potato: true
    prevent:
      premature: true
      mature: false
sugarCane:
  enabled: false
  delayHit: 3
  water:
    delay: 5
    drops:
      sugarCane: true
    prevent: false
  piston:
    delay: 5
    drops:
      sugarCane: true
    prevent: false