name: SuperWheat
main: de.dustplanet.superwheat.SuperWheat
version: ${project.version}-b${BUILD_NUMBER}
author: xGhOsTkiLLeRx
authors: [thescreem]
website: https://dev.bukkit.org/projects/superwheat
commands:
    superwheat:
        usage: /superwheat reload - Reload the plugin
        aliases: [superw, sw]
        description: Reloads the SuperWheat configuration file
permissions:
    SuperWheat.*:
        children:
            SuperWheat.wheat.*: true
            SuperWheat.netherWart.*: true
            SuperWheat.cocoaPlant.*: true
            SuperWheat.carrot.*: true
            SuperWheat.potato.*: true
            SuperWheat.sugarcane.*: true
            SuperWheat.reload: true
    SuperWheat.wheat.*:
        children:
            SuperWheat.wheat.destroying: true
            SuperWheat.wheat.regrowing: true
            SuperWheat.wheat.seeds: true
            SuperWheat.wheat.noseeds: true
    SuperWheat.wheat.destroying:
        default: op
        description: Allows destroying of crops
    SuperWheat.wheat.regrowing:
        default: op
        description: Allows regrowing of crops
    SuperWheat.wheat.seeds:
        default: op
        description: Allows getting of seeds, too
    SuperWheat.wheat.noseeds:
        default: op
        description: Doesn't require the seeds in the inventory
    SuperWheat.netherwart.*:
        children:
            SuperWheat.netherwart.destroying: true
            SuperWheat.netherwart.regrowing: true
            SuperWheat.netherwart.noseeds: true
    SuperWheat.netherwart.destroying:
        default: op
        description: Allows destroying of nether wart
    SuperWheat.netherwart.regrowing:
        default: op
        description: Allows regrowing of nether wart
    SuperWheat.netherwart.noseeds:
        default: op
        description: Doesn't require the nether wart in the inventory
    SuperWheat.cocoaplant.*:
        children:
            SuperWheat.cocoaplant.destroying: true
            SuperWheat.cocoaplant.regrowing: true
            SuperWheat.cocoaplant.noseeds: true
    SuperWheat.cocoaplant.destroying:
        default: op
        description: Allows destroying of cocoa plants
    SuperWheat.cocoaplant.regrowing:
        default: op
        description: Allows regrowing of cocoa plants
    SuperWheat.cocoaplant.noseeds:
        default: op
        description: Doesn't require the cocoa in the inventory
    SuperWheat.carrot.*:
        children:
            SuperWheat.carrot.destroying: true
            SuperWheat.carrot.regrowing: true
            SuperWheat.carrot.noseeds: true
    SuperWheat.carrot.destroying:
        default: op
        description: Allows destroying of carrots
    SuperWheat.carrot.regrowing:
        default: op
        description: Allows regrowing of carrots
    SuperWheat.carrot.noseeds:
        default: op
        description: Doesn't require the carrots in the inventory
    SuperWheat.potato.*:
        children:
            SuperWheat.potato.destroying: true
            SuperWheat.potato.regrowing: true
            SuperWheat.potato.noseeds: true
    SuperWheat.potato.destroying:
        default: op
        description: Allows destroying of potatoes
    SuperWheat.potato.regrowing:
        default: op
        description: Allows regrowing of potatoes
    SuperWheat.potato.noseeds:
        default: op
        description: Doesn't require the potatoes in the inventory
    SuperWheat.sugarcane.*:
        children:
            SuperWheat.sugarcane.regrowing: true
            SuperWheat.sugarcane.noseeds: true
    SuperWheat.sugarcane.regrowing:
        default: op
        description: Allows regrowing of sugar canes
    SuperWheat.sugarcane.noseeds:
        default: op
        description: Doesn't require the sugar canes in the inventory
    SuperWheat.reload:
         default: op
         description: Reloads the config
