# For help please either refer to the
# forum thread: http://bit.ly/superwheatthread
# or the bukkit dev page: http://bit.ly/superwheatpage
message: §6[SuperWheat] That plant isn't fully grown yet!
creative:
  dropsCreative: false
  blockCreativeDestroying: false
wheat:
  enabled: true
  trampling: true
  delayHit: 3
  water:
    delay: 5
    drops:
      wheat: true
      seed: false
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      wheat: true
      seed: false
    prevent:
      premature: true
      mature: false
netherWart:
  enabled: true
  delayHit: 3
  water:
    delay: 5
    drops:
      netherWart: true
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      netherWart: true
    prevent:
      premature: true
      mature: false
cocoaPlant:
  enabled: true
  delayHit: 3
  water:
    delay: 5
    drops:
      cocoaPlant: true
    prevent:
      premature: true
      mature: false
  piston:
    delay: 5
    drops:
      cocoaPlant: true
    prevent:
      premature: true
      mature: false