# For help please either refer to the
# forum thread: http://bit.ly/superwheatthread
# or the bukkit dev page: http://bit.ly/superwheatpage
message: §6[SuperWheat] That crop isn't fully grown yet!
delayHit: 3
water:
  drops:
    wheat: true
    seed: false
  prevent:
    premature: true
    mature: false
  delayWater: 5
  delay: 5
piston:
  delay: 5
  drops:
    wheat: true
    seed: false
  prevent:
    premature: true
    mature: false
creative:
  dropsCreative: false
  blockCreativeDestroying: false