# For help please either refer to the
# forum thread: http://bit.ly/superwheatthread
# or the bukkit dev page: http://bit.ly/superwheatpage
message: §6[SuperWheat] That crop isn't fully grown yet!
water:
  drops:
    wheat: true
    seed: false
  prevent:
    premature: true
    mature: false
  delayWater: 5
delayHit: 3
creative:
  dropsCreative: false
  blockCreativeDestroying: false