name: SuperWheat
main: de.dustplanet.superwheat.SuperWheat
version: 0.2
author: xGhOsTkiLLeRx
authors: [thescreem]
permissions:
    SuperWheat.*:
        children:
            SuperWheat.destroying: true
            SuperWheat.regrowing: true
    SuperWheat.destroying:
        default: op
        description: Allows destroying of crops
    SuperWheat.regrowing:
        default: op
        description: Allows regrowing of crops